Refactor module to add composer/whmcs meta and updated structure
monero-integrations/monerowhmcs pull request #42
Opened 2022-08-07 14:49 UTC by meramsey

This is a draft for now and will need to be merged after the https://github.com/monero-integrations/monerowhmcs/pull/41 is merged as it has some of its fixes but is minor when not factoring those in.

Basically this better restructures stuff to match WHMCS's recommended structure for these kinds of modules. 
https://github.com/WHMCS/sample-gateway-module
https://github.com/WHMCS/sample-addon-module

2022-08-08 19:44 UTC, serhack requested changes
Thank you a lot for the work you're doing. I appreciated the PR and issues you're creating.

Before reviewing, could you please update this PR with the actual branch?

2022-08-08 19:44 UTC, serhack commented on composer.json
> +    "third party gateway",
It's not a common "third party gateway", I would say "self-managed payment gateway", or "payment gateway".

2022-08-08 22:12 UTC, meramsey commented
> Thank you a lot for the work you're doing. I appreciated the PR and issues you're creating.
> 
> Before reviewing, could you please update this PR with the actual branch?

Should be all caught up and I merged the stuff from https://github.com/monero-integrations/monerowhmcs/pull/44 into this one as well as they would have had to be redone anyways after this merge due to the path changes for the addon module structure.

Should be all set :) @serhack

2022-08-09 12:56 UTC, serhack approved these changes
Thank you for the PR!

2022-08-09 12:56 UTC, merged